# Generated by Django 4.2.1 on 2023-05-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solids", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="votes",
            new_name="raw_value",
        ),
        migrations.RenameField(
            model_name="measurement",
            old_name="question",
            new_name="sensor",
        ),
        migrations.AlterField(
            model_name="sensor",
            name="sensor_description",
            field=models.TextField(max_length=500),
        ),
    ]
