# Generated by Django 4.2.1 on 2023-05-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_alter_choice_choice_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(max_length=200),
        ),
    ]
